routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::post('/login', [
    'uses'          => 'Auth\AuthController@login',
    'middleware'    => 'checkstatus',
]);
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/places','PlacesController');
Auth::routes(['register'=>false]);

app/Place.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Place extends Model
{
    public $timestamps= false;
    protected $table = 'places';
    protected $primaryKey = 'id';
    protected $fillable = [
        'name',
        'capacity',
        'status'
    ];
}

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    public $timestamps=false;
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role_id','status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    
    public function role(){
        $this->hasOne('App/Role');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
    
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PlacesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Place;
use Illuminate\Support\Facades\Gate;

class PlacesController extends Controller {

    public function __construct() {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $places = Place::all();
        
        return view('places.index', compact('places'));
    }
    
    public function getplaces() {
        return response()->json(Place::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        if (!Gate::allows('admin-only', auth()->user())) {
            echo 'sorry';
            return redirect(url()->previous())->withErrors('Anda tidak diizinkan masuk');;
        }
        return view('places.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        $request->validate([
            'name' => 'required',
            'capacity' => 'required|integer|max:1000'
        ]);
        $place = new Place([
            'name' => $request->get('name'),
            'capacity' => $request->get('capacity'),
            'status' => 1
        ]);
        $place->save();
        return redirect('/places')->with('success', 'Berhasil menambahkan data');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $place = Place::find($id);

        return view('places.edit', compact('place'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        $request->validate([
            'name' => 'required',
            'capacity' => 'required|integer|max:1000'
        ]);
        $place = Place::find($id);
        $place->name = $request->get('name');
        $place->capacity = $request->get('capacity');
        $place->status = 1;
        $place->save();
        return redirect('/places')->with('success', 'Berhasil mengubah data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        $place = Place::find($id);
        $place->delete();
        return redirect('/places')->with('success', 'Tempat telah dihapus');
    }

}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'My Project') }}</title>

        <!-- Fonts -->
        <link rel="dns-prefetch" href="//fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
        <link href="{{ asset('theme/vendor/font-awesome-5/css/fontawesome-all.min.css') }}" rel="stylesheet" media="all">

        <!-- Styles -->
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
        <link href="{{ asset('css/custom.css') }}" rel="stylesheet">


    </head>
    <body>

        <div id="app">
            <nav class="navbar navbar-expand-sm bg-info navbar-dark">
                <div class="container">
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Asset') }}
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <!--Center Of Navbar--> 
                        <ul class="navbar-nav mx-auto nav-menu">
                            <li>
                                <a href="{{route('places.index')}}"><i class="fa fa-lg fa-boxes"> </i>  Tempat</a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-lg fa-cube"> </i>  Barang</a>
                            </li>
                        </ul>

                        <!--Right Side Of Navbar--> 
                        <ul class="navbar-nav ml-auto">
                            <!--Authentication Links--> 
                            @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                            @endif
                            @else
                            <li class="nav-item dropdown">

                                <a id="navbarDropdown" class="topnav nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    <i class="fas fa-user"></i> {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="#">Pengaturan</a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                               document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                            @endguest
                        </ul>
                    </div>
                </div>
            </nav>

            <!--        <nav-component :menus="{{
                        json_encode(
                                [
                                    [
                                        'title'=>'Barang',
                                        'url'=>'#'
                                    ],
                                    [
                                        'title'=>'Tempat',
                                        'url'=>route('places.index')
                                    ]
                                ]
                            )
                            }}">
                    </nav-component>-->
            <div v-cloak>

                <div class="v-cloak--inline"> <!-- Parts that will be visible before compiled your HTML -->
                    <div class="text-center">
                        <br>
                        <i class="spinner-grow spinner-grow-sm text-danger"></i>
                        <i class="spinner-grow spinner-grow-sm text-info"></i>
                        <i class="spinner-grow spinner-grow-sm text-success"></i>
                    </div>
                </div>

                <div class="v-cloak--hidden"> <!-- Parts that will be visible After compiled your HTML -->
                    <!-- Rest of the contents -->
                    <main class="content">
                        <br>
                        @if(session()->get('success'))
                        <b-alert show variant="success" dismissible>
                            {{ session()->get('success') }}  
                        </b-alert>
                        @endif
                        @if ($errors->any())
                        <b-alert show variant="danger"  dismissible>
                            <ul>
                                @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </b-alert>
                        @endif
                        @yield('content')
                    </main>
                </div>

            </div>

        </div>
        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" type="text/javascript"></script>
    </body>
</html>

resources/views/layouts/base.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'My Project') }}</title>

        <!-- Fonts -->
        <link rel="dns-prefetch" href="//fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
        <link href="{{ asset('theme/vendor/font-awesome-5/css/fontawesome-all.min.css') }}" rel="stylesheet" media="all">

        <!-- Styles -->
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
        <link href="{{ asset('css/custom.css') }}" rel="stylesheet">


    </head>
    <body>
        
        <div id="app">
<div class="container">
    <br>
            <main class="content mx-auto">
                @yield('content')

            </main>
        </div>
        
            
        </div>
        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" type="text/javascript"></script>
    </body>
</html>

resources/views/places/create.blade.php
@extends('layouts.app')

@section('content')
<div class="card uper">
  <div class="card-header">
   Tambah Tempat
  </div>
  <div class="card-body">

      <form method="post" action="{{ route('places.store') }}">
          <div class="form-group">
              @csrf
              <label for="name">Nama Tempat:</label>
              <input type="text" required class="form-control" name="name" max="50" size='50'/>
          </div>
          <div class="form-group">
              <label for="price">Kapasitas Max :</label>
              <input type="number" required class="form-control" max="1000" maxlength="1000" min="0" name="capacity"/>
          </div>
          <button type="submit" class="btn btn-primary">Tambah</button>
      </form>
  </div>
</div>
@endsection

resources/views/places/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="card uper">
  <div class="card-header">
    Ubah Tempat
  </div>
  <div class="card-body">
      <form method="post" action="{{ route('places.update',$place->id) }}">
          @csrf
          @method('PATCH')
          <div class="form-group">
              
              <label for="name">Nama Tempat:</label>
              <input type="text" required class="form-control" name="name" max="50" size='50' value="{{$place->name}}"/>
          </div>
          <div class="form-group">
              <label for="price">Kapasitas Max :</label>
              <input type="number" required class="form-control" max="1000" maxlength="1000" min="0" name="capacity" value='{{$place->capacity}}'/>
          </div>
          <button type="submit" class="btn btn-primary">Ubah</button>
      </form>
  </div>
</div>
@endsection

resources/views/places/index.blade.php
@extends('layouts.app')
@section('content')
<div >
    <div class="col-lg-12">
        <h2>Tempat</h2>
    </div>
    <br/>
    <places-component :items="{{json_encode($places)}}"></places-component>
<!--    <table class="table table-striped">
        <thead>
            <tr>
                <td>Nama Tempat</td>
                <td>Kapasitas Maksimum</td>
                <td colspan="2">Action</td>
            </tr>
        </thead>
        <tbody>
            @if($places->count()==0)
            <tr>
                <td colspan="3">
                    Tidak ada data  
                </td>
            </tr>
            @endif
            @foreach($places as $place)
            <tr>
                <td>{{$place->name}}</td>
                <td>{{$place->capacity}}</td>
                <td><a href="{{ route('places.edit',$place->id)}}" class="btn btn-primary">Edit</a></td>
                <td>
                    <form action="{{ route('places.destroy', $place->id)}}" method="post">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger" type="submit">Delete</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>-->
    <br>
</div>

@endsection